OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/djangotweet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tweetapp.urls')),
    path("",include('django.contrib.auth.urls'))
]

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path('',views.listtweet,name='listtweet'),#atilsamancioglu.com/tweetapp/
    path('addtweet/', views.addtweet,name='addtweet'),#atilsamancioglu.com/tweetapp/addtweet
    path('addtweetbyform/', views.addtweetbyform, name='addtweetbyform'),#atilsamancioglu.com/tweetapp/addtweetbyform
    path('addtweetbymodelform/', views.addtweetbymodelform, name='addtweetbymodelform'),#atilsamancioglu.com/tweetapp/addtweetbymodelform
    path('signup/', views.SingUpView.as_view(), name="signup"),
    path('deletetweet/<int:id>', views.deletetweet, name="deletetweet"),
]

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tweet(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    message = models.CharField(max_length=200)

    def __str__(self):
        return f"Tweet User: {self.username} message: {self.message}"
        

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/tweetapp/forms.py
from django import forms
from django.forms import ModelForm
from tweetapp.models import Tweet

class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(label="Nickname",max_length=50)
    message_input = forms.CharField(label="Message",max_length=200, widget=forms.Textarea(attrs={"class": "tweetmessage"}))


class AddTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ["username", "message"]
        

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/tweetapp/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse, reverse_lazy
from tweetapp.forms import AddTweetForm, AddTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

# from . import forms

# Create your views here.

def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict = {"tweets": all_tweets}
    return render(request,'tweetapp/listtweet.html', context= tweet_dict)

@login_required(login_url="/login")
def addtweet(request):
    if request.POST:
        message = request.POST["message"]
        #tweet = models.Tweet(nickname, message)
        #tweet.save()
        models.Tweet.objects.create(username=request.user, message=message)
        return redirect(reverse('tweetapp:listtweet'))
    else:
        return render(request,'tweetapp/addtweet.html')


def addtweetbyform(request):
    if request.method == "POST":
        form = AddTweetForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname_input"]
            message = form.cleaned_data["message_input"]
            models.Tweet.objects.create(nickname=nickname, message=message)
            return redirect(reverse('tweetapp:listtweet'))
        else:
            print("Error in form !")
            return render(request,'tweetapp/addtweetbyform.html', context={"form": form})
        #print(request.POST)
    else:
        form = AddTweetForm()
        return render(request,'tweetapp/addtweetbyform.html', context={"form": form})
    
def addtweetbymodelform(request):
    if request.method == "POST":
        form = AddTweetModelForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname"]
            message = form.cleaned_data["message"]
            models.Tweet.objects.create(nickname=nickname, message=message)
            return redirect(reverse('tweetapp:listtweet'))
        else:
            print("Error in form !")
            return render(request,'tweetapp/addtweetbymodelform.html', context={"form": form})
    #print(request.POST)
    else:
        form = AddTweetModelForm()
        return render(request,'tweetapp/addtweetbymodelform.html', context={"form": form})
    
@login_required  
def deletetweet(request, id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect('tweetapp:listtweet')

class SingUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Tweet App</title>
    <link rel="stylesheet" href="{% static 'tweetapp/customform.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'tweetapp:listtweet' %}">Tweet App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'tweetapp:addtweet' %}">Add Tweet</a>
              </li>
              <!--
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'tweetapp:addtweetbyform' %}">Add Tweet By Form</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'tweetapp:addtweetbymodelform' %}">Add Tweet By Model Form</a>
              </li>
              -->
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'logout' %}?next=/">Logout</a>
              </li>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'tweetapp:signup' %}">SignUp</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    
    {% block content %}
    
    {% endblock content %}

</body>
</html>

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="container" style="width:50%";>
      <!--
    <div class="mb-3">
      <label for="nickname" class="form-label">Nick Name</label>
      <input type="text" class="form-control" id="nickname" name="nickname">
    </div>
    -->
    <div class="mb-3">
      <label for="message" class="form-label">Message</label>
      <input type="text" class="form-control" id="message" name="message">
    </div>
    <button type="submit" class="btn btn-primary">Send Tweet</button>
  </div>
  </form>
{% endblock content %}

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/tweetapp/templates/tweetapp/addtweetbyform.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Add Tweet By Form Page</h1>
<div class="container tweetform">
  <form action="" method="POST">
      {% csrf_token %}

      <div class="mb-3">
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Send 1 Tweet</button>
      </div>
      <br><br>
      <div class="mb-3">
        {{form.nickname_input.label_tag}}
        {{form.nickname_input}}
      </div>

      <div class="mb-3">
        {{form.message_input.label_tag}}
        {{form.message_input}}
      </div>
      <button type="submit" class="btn btn-primary">Send 2 Tweet</button>
      <br><br>
      {%for field in form%}
      <div class="form-control">
        {{field.label_tag}}
        {{field}}
      <div>
      {%endfor%}
      <br>
      <button type="submit" class="btn btn-primary">Send 3 Tweet</button>
    </form>
  </div>
{% endblock content %}

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/tweetapp/templates/tweetapp/addtweetbymodelform.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Add Tweet By Model Form Page</h1>
<div class="container tweetform">
    <form action="" method="POST">
        {% csrf_token %}
  
    {%for field in form%}
    <div class="mb-3">
        {{field.label_tag}}
        {{field}}
      
    <div>
    {%endfor%}
    <br>
    <button type="submit" class="btn btn-primary">Send 4 Tweet</button>
    </form>
  </div>
{% endblock content %}

OneDrive/Masaüstü/100_gunluk_programlama_kampı/DjangoTweet/djangotweet/tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}

{% block content %}
<!--
<h1>List Tweet Page</h1>
<ul>
    {% for tweet in tweets %}
        <li><h2>{{tweet.nickname}} -> {{tweet.message}}</h2></li>
    {% endfor %}
<ul>
    -->
    <div class="container" style="width: 50%">
    {% for tweet in tweets %}
        <div class="card" style="padding:2px">
            <div class="card-header" style="background-color:cornflowerblue;">
                <h4> {{tweet.username}} </h4>
            </div>
            <div class="card-body">
                <p class="card-text">{{tweet.message}}</p>
            </div>
            {% if tweet.username == user %}
            <a href="{% url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a> 
            {% endif %}
        </div>
    {% endfor %}
    </div>
{% endblock %}